services:
  web:
    image: simple-leave-tracket-web
    build:
      context: ./web/simple-leave-tracker
      dockerfile: ../../Dockerfile.web
    ports:
      - "3000:3000"
    networks:
      - backend-api

  api:
    image: simple-leave-tracket-api
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - "8000:8080"
    environment:
      DB_HOST: db
      DB_USER: leave_tracker
      DB_PASSWORD: Password
      DB_NAME: leave_tracker
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-api
      - backend-db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password
      POSTGRES_USER: leave_tracker
      POSTGRES_DB: leave_tracker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leave_tracker"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend-db

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    ports:
      - 1990:1990
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus


networks:
  backend-api:
  backend-db:
