services:
  web:
    image: simple-leave-tracket-web
    build:
      context: ./web/simple-leave-tracker
      dockerfile: ../../Dockerfile.web
    ports:
      - "3000:3000"

  api:
    image: simple-leave-tracket-api
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - "8000:8080"