services:
  web:
    image: simple-leave-tracket-web
    build:
      context: ./web/simple-leave-tracker
      dockerfile: ../../Dockerfile.web
    ports:
      - "3000:3000"
    networks:
      - backend-api

  api:
    image: simple-leave-tracket-api
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - "8000:8080"
    depends_on:
      - db
    networks:
      - backend-api
      - backend-db

  db:
    image: postgres:lattest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password
      POSTGRES_USER: leaveTracker
      POSTGRES_DB: leave_tracker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend-db

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus


networks:
  backend-api:
  backend-db:
