services:
  web:
    image: simple-leave-tracket-web
    build:
      context: ./web/simple-leave-tracker
      dockerfile: ../../Dockerfile.web
    ports:
      - "3000:3000"
    networks:
      - backend-api

  api:
    image: simple-leave-tracket-api
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - "8000:8080"
    networks:
      - backend-api
      - backend-db

  db:
    image: postgres:lattest
    ports:
      - "5432:5432"
    networks:
      - backend-db

networks:
  backend-api:
  backend-db:
