FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -v -trimpath -ldflags='-s -w' -o server ./cmd/server

FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/server /server

CMD ["/server"]